<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyName>VagEepromEditor</AssemblyName>
    <RootNamespace>App.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Models\App.Models.csproj" />
    <ProjectReference Include="..\App.Core\App.Core.csproj" />
    <ProjectReference Include="..\App.Crypto\App.Crypto.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>

</Project>
